# попробовал сделать POSTGRES_DB: "notes_db""
#POSTGRES_USER: "postgres" POSTGRES_PASSWORD: "12345", но не заработало

version: "3.9"
services:
  postgres:
    image: postgres:13
    volumes:
      - ./migration/create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      POSTGRES_DB: "notes_db"
      POSTGRES_USER: "buba"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"